package com.venkata.ds.graphtheory;

public enum GraphType {

    DIRECTED_WEIGHTED,
    DIRECTED_UNWEIGHTED,
    UNDIRECTED_WEIGHTED,
    UNDIRECTED_UNWEIGHTED,
    CYCLIC_UNWEIGHTED,
    CYCLIC_WEIGHTED,
    DAG_WEIGHTED,
    DAG_UNWEIGHTED

    ;

}
